# Generated by Django 3.2.4 on 2021-06-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=25, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('nombreProducto', models.CharField(max_length=25, verbose_name='Nombre de producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio de producto')),
                ('cantProducto', models.IntegerField(verbose_name='Cantidad de producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugio.categoria')),
            ],
        ),
    ]
